Repository COSC481W-2022Winter/capstone-team-mercury-cosc481w-2022, pull requests merged in 2022-04, with the labels that each got.

#48 Revert "feat: Added the Explore page"
  backend/server.js
Labels: Bug, Node/Express, Sprint 3, Completed

#51 Revert "feat: API tags"
  backend/api/searchAPI.js
Labels: Bug, Node/Express, Sprint 3, Completed

#49 Ley main page filter
  backend/api/contentfeedAPI.js
  backend/models/user.js
  src/components/placeholderPost/noPostsPlaceholder.js
  src/pages/feed.js
Labels: improvement, React/HTML, Node/Express, MongoDB, Sprint 3, Completed

#53 Mitch follow
  backend/api/profileAPI.js
  src/components/Comments.js
  src/components/followButton.js
  src/components/profileBlock.js
  src/pages/feed.js
Labels: feature, Bug, React/HTML, Node/Express, Sprint 3, Completed

#52 feat: Implement explore page
  backend/api/searchAPI.js
  src/App.js
  src/components/Navigation.js
  src/pages/explore.js
  src/pages/page.css
Labels: feature, React/HTML, Node/Express, Sprint 3, Completed

#54 feat: Implemented profile picture and banners
  backend/api/profileAPI.js
  backend/api/userAPI.js
  backend/models/user.js
  backend/utils/cloudinary.js
  backend/utils/multer.js
  src/components/post.js
  src/components/profileBlock.js
  src/pages/editProfile.js
  src/pages/page.css
Labels: feature, Bug, React/HTML, Node/Express, MongoDB, Sprint 3, Completed

#56 fix: End of sprint 3 cleanup
  backend/api/contentfeedAPI.js
  backend/api/loginAPI.js
  backend/api/postAPI.js
  backend/api/profileAPI.js
  backend/api/searchAPI.js
  backend/api/userAPI.js
  package-lock.json
  package.json
  src/components/Navigation.js
  src/components/followButton.js
  src/components/logout.js
  src/pages/editProfile.js
  src/pages/explore.js
  src/pages/feed.js
  src/pages/login.js
  src/pages/newPost.js
  src/pages/page.css
  src/pages/register.js
  src/pages/search.js
Labels: improvement, Bug, React/HTML, Node/Express, Sprint 3, Completed

#67 feat: Apply sprint 4 database changes
  backend/models/notification.js
  backend/models/user.js
Labels: feature, MongoDB, Sprint 4, Completed

#69 feat: Implemented notifications
  backend/api/notificationAPI.js
  backend/api/postAPI.js
  backend/api/profileAPI.js
  backend/models/user.js
  backend/server.js
  src/App.js
  src/components/Navigation.js
  src/components/getUsername.js
  src/components/notif.js
  src/components/placeholderPost/noNotifsPlaceholder.js
  src/components/placeholderPost/notifPlaceholder.js
  src/pages/notifications.js
  src/pages/page.css
  src/pages/userProfile.js
Labels: feature, Bug, Feedback, React/HTML, Node/Express, MongoDB, Sprint 4, Completed

#71 Deleting posts
  backend/api/postAPI.js
  backend/api/userAPI.js
  src/components/deletePosts.js
  src/components/deleteUser.js
  src/pages/accountSettings.js
Labels: feature, In Progress, Feedback, React/HTML, Node/Express, Sprint 4

#73 Mitch likes visibility
  backend/api/userAPI.js
  src/components/likesVisibilityButtton.js
  src/pages/accountSettings.js
  src/pages/userProfile.js
Labels: feature, React/HTML, Node/Express, Sprint 4, Completed

#72 Ley changing password
  backend/api/profileAPI.js
  backend/api/userAPI.js
  src/components/changePassword.js
  src/pages/accountSettings.js
  src/pages/editProfile.js
Labels: feature, Feedback, React/HTML, Node/Express, Sprint 4, Completed

#77 kanza profile likes posts
  backend/api/postAPI.js
  backend/api/userAPI.js
  backend/models/user.js
  src/components/profileLikes.js
  src/components/profilePosts.js
  src/pages/page.css
  src/pages/userProfile.js
Labels: feature, Feedback, React/HTML, Node/Express, MongoDB, Sprint 4, Completed

#76 feat: Add Bootstrap Styling
  package-lock.json
  package.json
  src/App.js
  src/components/Navigation.js
  src/components/TagAdder.js
  src/components/deleteUser.js
  src/components/logout.js
  src/components/mustLogin.js
  src/components/notif.js
  src/components/post.js
  src/components/profileBlock.js
  src/pages/editProfile.js
  src/pages/login.js
  src/pages/newPost.js
  src/pages/page.css
  src/pages/register.js
  src/pages/search.js
Labels: improvement, React/HTML, Sprint 4, Refactor

#78 Wrathbun sprint4 cleanup
  backend/api/contentfeedAPI.js
  backend/api/searchAPI.js
  backend/api/userAPI.js
  package-lock.json
  src/components/Navigation.js
  src/components/changePassword.js
  src/components/deletePosts.js
  src/components/likesVisibilityButton.js
  src/components/post.js
  src/components/postPostPage.js
  src/components/profileLikes.js
  src/components/profilePosts.js
  src/pages/accountSettings.js
  src/pages/feed.js
  src/pages/login.js
  src/pages/page.css
  src/pages/search.js
  src/pages/userProfile.js
Labels: improvement, Bug, React/HTML, Node/Express, Sprint 4, Completed

#80 fix: fixed edit profile styling
  src/pages/editProfile.js
  src/pages/page.css
Labels: Bug, Feedback, React/HTML, Sprint 4, Completed
