Repository COSC481W-2022Winter/capstone-team-mercury-cosc481w-2022, pull requests merged in 2022-02, with the labels that each got.

#8 feat: Added database connectivity
  backend/cutestpawDB.js
  backend/models/post.js
  backend/models/user.js
  backend/server.js
Labels: feature, MongoDB, Sprint 1, Completed

#9 Backend profile
  backend/api/profileAPI.js
Labels: feature, Node/Express, Sprint 1, Completed

#10 Content Feed
  .gitignore
  backend/api/contentfeedAPI.js
  backend/server.js
  package-lock.json
  package.json
  src/App.js
  src/components/About.js
  src/components/Contact.js
  src/components/Error.js
  src/components/Home.js
  src/components/Navigation.js
  src/components/index.css
  src/components/placeholderPost/placeholderPost.js
  src/components/placeholderPost/placeholderpost.css
  src/components/tictac.js
  src/index.css
  src/index.js
  src/pages/feed.js
Labels: feature, React/HTML, Node/Express, MongoDB

#15 feat: Added profile page
  src/App.js
  src/pages/profile.css
  src/pages/profile.js
Labels: feature, React/HTML, Sprint 1, Completed

#16 Olga wrathbun create acct
  backend/api/userAPI.js
  backend/server.js
  src/pages/register.js
Labels: feature, React/HTML, Sprint 1, Completed

#18 refactor: Complete sprint 1 refactor
  backend/api/testAPI.js
  backend/frontend/login.js
  backend/server.js
  src/App.js
  src/components/About.js
  src/components/Contact.js
  src/components/Error.js
  src/components/Home.js
  src/components/Navigation.js
  src/components/placeholderPost/placeholderPost.js
  src/components/tictac.js
  src/pages/feed.js
  src/pages/login.js
  src/pages/newPost.js
  src/pages/profile.js
Labels: improvement, feature, Bug, React/HTML, Node/Express, Sprint 1, Completed, Refactor
