Repository COSC481W-2022Winter/capstone-team-mercury-cosc481w-2022, pull requests merged in 2022-03, with the labels that each got.

#30 Wrathbun mitchell profile viewing
  backend/server.js
  package-lock.json
  package.json
  src/App.js
  src/components/getUsername.js
  src/components/mustLogin.js
  src/pages/feed.js
  src/pages/newPost.js
  src/pages/userProfile.js
Labels: feature, React/HTML, Node/Express, Sprint 2, Completed, Refactor

#28 feat: Improved posts image uploading
  backend/api/contentfeedAPI.js
  backend/api/postAPI.js
  backend/models/post.js
  package-lock.json
  package.json
  src/pages/feed.js
  src/pages/newPost.js
Labels: improvement, feature, Feedback, React/HTML, Node/Express, Sprint 2

#31 Mitchell comments frontend
  backend/api/contentfeedAPI.js
  backend/api/postAPI.js
  backend/models/post.js
  src/components/Comments.js
  src/pages/feed.js
Labels: feature, Feedback, React/HTML, Sprint 2, Completed

#32 fix: Fix image display issues
  backend/api/postAPI.js
  backend/models/post.js
  src/pages/feed.js
  src/pages/newPost.js
Labels: Bug, Sprint 2, Completed

#34 feat: implement editing profiles
  backend/api/profileAPI.js
  src/App.js
  src/components/Navigation.js
  src/pages/editProfile.js
  src/pages/profile.css
  src/pages/userProfile.js
Labels: Feedback, React/HTML, Sprint 2, Completed

#33 feat: implement likes
  backend/api/postAPI.js
  backend/models/post.js
  src/components/Likes.js
  src/img/liked.png
  src/img/unliked.png
  src/pages/feed.js
Labels: feature, Feedback, React/HTML, Sprint 2, Completed

#35 refactor: Complete end of sprint 2 refactor
  README.md
  src/App.css
  src/components/Comments.js
  src/components/Navigation.js
  src/components/index.css
  src/img/logo.png
  src/pages/editProfile.js
  src/pages/feed.js
  src/pages/login.css
  src/pages/login.js
  src/pages/newPost.js
  src/pages/newpost.css
  src/pages/page.css
  src/pages/profile.css
  src/pages/profile.js
  src/pages/register.js
  src/pages/userProfile.js
Labels: improvement, Bug, Feedback, React/HTML, Sprint 2, Completed, Refactor

#42 refactor: Extract posts and profile block
  src/App.js
  src/components/post.js
  src/components/profileBlock.js
  src/pages/feed.js
  src/pages/page.css
  src/pages/search.js
  src/pages/userProfile.js
Labels: Feedback, React/HTML, Sprint 3, Completed, Refactor

#43 feat: Implement searching
  backend/api/searchAPI.js
  backend/models/post.js
  backend/server.js
  src/components/Navigation.js
  src/components/profileBlock.js
  src/pages/page.css
  src/pages/search.js
  src/pages/userProfile.js
Labels: improvement, feature, React/HTML, Node/Express, MongoDB, Sprint 3, Completed

#44 feat: Add tags to posts
  backend/api/postAPI.js
  package-lock.json
  package.json
  src/components/TagAdder.js
  src/components/Tags.js
  src/components/tags.css
  src/pages/newPost.js
Labels: feature, React/HTML, Node/Express, MongoDB, Sprint 3, Completed

#46 fix: added missing file
  backend/api/postAPI.js
  package-lock.json
  package.json
  src/components/TagAdder.js
  src/components/Tags.js
  src/components/post.js
  src/components/tags.css
  src/pages/newPost.js
Labels: feature, React/HTML, Node/Express, MongoDB, Sprint 3, Completed
